### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO29_Road_Hopping_1A.WL_Rosche#1]
**Миссия:**

- [x] Поставить маркер MSR 493 между чекпоинтом и OBJ CITY, а то не читается. Сделать второй маркер для MSR 71 (поставить восточнее)
- [x] CCP и FARP можно поместить ближе к зоне БД. Скорее всего их подвинут вперед, но будут делать это вслепую, так что можно сразу их держать ближе к краю зоны и протестить что они спавнятся не в какой-нибудь яме
- [x] Брифинг: Обстановка: "Войска противника" - кто это такие? "Вашему первому взводу" - а мы кто такие? Какой год вообще, где мы и зачем? В обстановке должны быть явно обозначены кто и куда воюет, см http://naf.tacticalshift.ru/mission_making;mission_editor;requirements#%D0%B1%D1%80%D0%B8%D1%84%D0%B8%D0%BD%D0%B3 
- [x] Брифинг: Обстановка: Я бы предпочел иметь информацию об обороне противника в пункте Враждебные силы или Выполнение, а не искать ее в Обстановке. Большая часть второго абзаца избыточно для ознакомления с тем что вообще происходит.
- [x] Брифинг: Враждебные силы: Используй цифры для числительных, ставь точки и пустые строки между заголовком (ВС РФ - Регулярные войска: (пустая строка) 2 мотострелковых взвода на БТР/БМП; (новая строка), около 3-х Т-72. (пустая строка) статики. (новая строка)арта. (новая строка) ПВО.).
- [x] Брифинг: Выполнение: добавь пустые строки, чтобы читалось лучше.
- [x] Поставь маркер для вертолетов, чтобы понимать откуда будут лететь.
- [x] Брифинг: Замечания - вот тут бы про редеплой и резервы написал, сколько доступно пихоты, что в резерве.
- [x] Брифинг: Замечания для ГСО: Хороший повод дать врагам возможность позвать немного штурмовой авиации/ми-24, а игрокам дать пару стингеров.
- [x] На слоттинге платун лидер написан как 1'6 Leader (возможно чото криво поставилось через 3ден тулз, но для стандартизации лучше бы поправить и завести баг на тсф). Из-за этого по идее не будет работать POM
11. А как зероинг крутить на рхсном абрамсе?
- [x] На чекпоинте стоят родблоки - если пацаны отступают то лучше всю дорогу перекрыть к хуям, еще и мин насыпать вокруг. Аналогично с дорогами на севере и юге, идущими к точке - сделай там какие сгоревшие машины (гражданские, пиндосские и русские), а рядом кое где кинь ПТ мины (и/или противопехотных растяжек заодно)
- [x] Часть техники (например БМД) лучше спрятать в застройке и дать ГСО возможность ее заюзать в директ контроле.
- [x] А в чом прикол что на первом же блокпосте - главная дорого ВООБЩЕ никем не защищается? пулемет смотрит южнее, БТР стоит открытым боком и смотрит севернее, а вдоль дороги можно просто на танке приехать, никто и не почешется (там даже ПТ нет). Лучше бы чекпоинт чисто бункер чтобы отсидеть если будет арта (а она конечно будет), перекрытая дорога, и наблюдательный пункт на юго-западе (там трилайн буквой Г и на северо-западе в лесу, с них дорогу видно, накопать там окопов и замаскировать кустиками можно арту наводить и птшить дорогу)
- [x] Attributes - Dynamic simulation - false
- [x]  Машинки на старте оче плотно стоят, если два игрока водителя врежутся то может случится пиздося

**tSF:**
- [x]  Едитор юнит бехавиор это для того чтобы сделать всяких лидеров боевиков сдаваться, для дунай бехевиора он не нужен.
- [x]  Для техники в укрытии ставь только командера и ганнера, дривер мне кажется нахуй не нужен (умеет только застревать в окопе)
- [x]  FARP - выключить ProproptionMode для всех видов перезарядок, а то ехать долго, еще потом стоять долго.

**Dyani:**

**Gear:**
- [x] ЕМНИП пиндосы полноразмерные м249 уже не особо пользуют. Как минимум приклад складываемый, как максимум еще и короткий ствол (тяжило целый носить).
- [x] М240 можно и рхсный брать. В машинках лежит куповский.
- [x] Танкам не нужно таскать 30 станагов, 2 м136 и 2 ПТ мины(!), пускай там дефолтный гир лежит.
- [x] Может в 1'3 больше дальномеров? А то карта плоская, дистанции очень плохо считывать по биноклю

**Comment by 10Dozen** [comment]
Алсо - там обновился скрипт логгера - https://github.com/10Dozen/dzn_tSFramework/tree/master/dzn_brv -- скачай и вот эту часть замени в свое миссии

**Comment by OneScheer** [comment]
1. Переставлены маркеры
2.  CCP и FARP по умолчанию расположены ближе к FEBA
3. Переписан брифинг
4. Переписан брифинг
5. Переписан брифинг
6. Переписан брифинг
7. Переписан брифинг
8. Переписан брифинг
9. Переписан брифинг 
10. Исправлено  
11.  Зероинг автоматический через T
12.  Чекпоинт изменён, вместо БТР - БМП,  добавлены сгоревшие машины и эмбиент дым
13.  БМП-3 и БМП-2 спрятаны в застройке, к ним применён кит с полным экипажем
14.  Добавлен наблюдательный пункт и ПТУР в Г-образную зелёнку к юго-западу от блокпоста.
15. исправлено
16.  исправлено

### Gear

1. Добавлен более новый модерновый M249 
2. М240 изменён на РХС
3. В танках только медкиты и репэир киты
4. Изменены все бинокли на дальномеры

**Comment by 10Dozen** [comment]
Переименовал Platoon Leader в миссии, а в тСФ Airborne SUpport, Artillery Support осталось ,"1'6 %1Platoon Leader@1'6".

 В Artillery Support довольно странный "1'4 Squad Leader**@1'3**" вместо 1'3 Squad Leader@1'3

**Comment by OneScheer** [comment]
Исправил
