### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by Comrade333** [rempopo/CO29_Road_Hopping_1A.WL_Rosche#2]
1. Город кажется пустым, добавь всяких машинок для атмосферы.
2. Там классные рубашечки добавили в рхс вместо комбат юниформ, выглядит стилёво, мб поменять?
3. Мб на блокпост давить какую-нибудь бмп вместо бтр? а то в городе танкови и бэхи в засадах, а на подступах слишком изи.

**Comment by OneScheer** [comment]
1. Добавил
2. Поменял на новую форму
3. На блокпосте бтр поменял на бмп-2
